#!/usr/bin/env node
// Write `src/envelope/protocol-keys.ts` from the canonical envelope schema.
//
// `protocol/schema/v1/envelope.schema.json` is the protocol. The TypeScript
// SDK used to repeat its field names as six hand-written arrays, so the
// schema and the validator agreed only for as long as somebody remembered to
// change both. This generator makes the schema the single place a field name
// is written: the arrays below are read out of it, and `--check` fails when
// the checked-in file no longer matches, which is what the test runs.
//
// Usage:
//   node scripts/protocol-keys.mjs            write src/envelope/protocol-keys.ts
//   node scripts/protocol-keys.mjs --check    exit 1 if it would change

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(here, "..");
const repoRoot = resolve(packageRoot, "..", "..");
const schemaPath = join(repoRoot, "protocol", "schema", "v1", "envelope.schema.json");
const outputPath = join(packageRoot, "src", "envelope", "protocol-keys.ts");
const outputLabel = "src/envelope/protocol-keys.ts";

/** Each envelope shape the SDK validates, and the schema definition it comes from. */
const SHAPES = [
  { constant: "REQUEST", def: "request" },
  { constant: "REQUEST_META", def: "requestMeta" },
  { constant: "RESPONSE", def: "response" },
  { constant: "EVENT", def: "event" },
  { constant: "ERROR_ENVELOPE", def: "error" },
  { constant: "ERROR_BODY", def: "errorBody" },
  { constant: "REPLAY_PARAMS", def: "replayParams" },
];

function definition(schema, name) {
  const found = schema.$defs?.[name];
  if (!found) throw new Error(`${schemaPath} has no $defs/${name}`);
  if (found.additionalProperties !== false) {
    throw new Error(`$defs/${name} allows extra properties; the SDK rejects them`);
  }
  const allowed = Object.keys(found.properties ?? {});
  if (allowed.length === 0) throw new Error(`$defs/${name} declares no properties`);
  return { allowed, required: found.required ?? [] };
}

function literal(values) {
  return `[${values.map((value) => JSON.stringify(value)).join(", ")}] as const`;
}

function render(schema) {
  const lines = [
    "// Generated by scripts/protocol-keys.mjs from",
    "// protocol/schema/v1/envelope.schema.json. Do not edit by hand: change the",
    "// schema and run `npm run generate:protocol`. The drift gate is",
    "// tests/protocol/envelope-keys.mjs.",
    "",
    `/** ${schema.title}. */`,
    `export const PROTOCOL_TITLE = ${JSON.stringify(schema.title)};`,
    "",
  ];
  for (const { constant, def } of SHAPES) {
    const { allowed, required } = definition(schema, def);
    lines.push(`/** Every field \`${def}\` allows, in schema order. */`);
    lines.push(`export const ${constant}_KEYS = ${literal(allowed)};`);
    lines.push(`/** The fields \`${def}\` requires. */`);
    lines.push(`export const ${constant}_REQUIRED = ${literal(required)};`);
    lines.push("");
  }
  return lines.join("\n");
}

const schema = JSON.parse(readFileSync(schemaPath, "utf8"));
const rendered = render(schema);
const check = process.argv.includes("--check");
const current = (() => {
  try {
    return readFileSync(outputPath, "utf8");
  } catch {
    return null;
  }
})();

if (check) {
  if (current === rendered) {
    console.log(`${outputLabel} matches ${schemaPath}`);
    process.exit(0);
  }
  console.error(
    current === null
      ? `${outputLabel} is missing; run npm run generate:protocol`
      : `${outputLabel} no longer matches the envelope schema; run npm run generate:protocol`,
  );
  process.exit(1);
}

if (current === rendered) {
  console.log(`${outputLabel} already current`);
} else {
  writeFileSync(outputPath, rendered);
  console.log(`wrote ${outputPath} from ${schemaPath}`);
}
