use super::ToolInfo;

pub(super) fn built_in_tools() -> Vec<ToolInfo> {
    vec![
        ToolInfo::new("list_dir", "List a directory under cwd; optional depth recursively includes children"),
        ToolInfo::new("read_file", "Read a UTF-8 text file under cwd, capped at 512KB unless a selector narrows output; returns sha256, snapshot path#TAG, visual numbered lines, content; selectors support ranges, comma ranges, raw, and conflicts"),
        ToolInfo::new("read_binary_file", "Read one binary file under cwd as base64, capped at 512KB"),
        ToolInfo::new("read_image", "Read one PNG, JPEG, GIF, or WebP image under cwd as base64 with mime type and dimensions, capped at 512KB"),
        ToolInfo::new("read_archive", "List archive entries or read one entry from .zip, .tar, .tar.gz, or .tgz under cwd as text, binary base64, document text, or image metadata; text/document entries support line ranges"),
        ToolInfo::new("read_document", "Extract readable text from one document under cwd; supports text, HTML, JSON, CSV/TSV, XML/RSS/Atom, notebooks, and basic PDF text streams; supports line ranges; capped at 512KB output"),
        ToolInfo::new("read_sqlite", "Read a SQLite database under cwd: list tables, inspect a table, fetch one row by primary key, or run a read-only SELECT/WITH query"),
        ToolInfo::new("search_text", "Search one file for a literal string, capped at 50 line matches; case-insensitive by default"),
        ToolInfo::new("search_files", "Recursively search text files under cwd for a literal string, capped at 500 matches; supports path/paths, hidden, gitignore, caseSensitive, limit, and skip; case-insensitive by default"),
        ToolInfo::new("glob_paths", "Find files and directories under cwd with simple glob patterns; supports * and ** plus hidden, gitignore, limit, and skip"),
        ToolInfo::new("grep_regex", "Search text files under cwd with a JavaScript regular expression, capped at 500 matches; supports path/paths, hidden, gitignore, multiline, caseSensitive, limit, and skip; case-insensitive by default"),
        ToolInfo::new("write_file", "Create or overwrite a UTF-8 text file under cwd; overwrites require expectedSha256 from read_file; returns sha256 and visual diff; requires --allow-write"),
        ToolInfo::new("apply_patch", "Apply exact one-occurrence string replacements to an existing UTF-8 file; returns sha256 and visual diff; requires expectedSha256 and --allow-write"),
        ToolInfo::new("edit_file", "Apply line-based edits to a UTF-8 file under cwd; returns sha256 and visual diff; requires expectedSha256 and --allow-write"),
        ToolInfo::new("edit", "Apply an OMP-style anchored visual patch string with [path#TAG], SWAP/DEL/INS/REM/MV and safe block hunks; returns visual diffs; requires --allow-write"),
        ToolInfo::new("delete_file", "Delete one UTF-8 file under cwd; returns visual diff; requires expectedSha256 and --allow-write"),
        ToolInfo::new("move_file", "Move or rename one file under cwd; returns rename preview; requires expectedSha256 and --allow-write"),
        ToolInfo::new("run_command", "Run a shell command in cwd; requires --allow-command; supports env overrides; timeout defaults to 30s and maxes at 120s"),
        ToolInfo::new("run_process", "Run one process with argv array in cwd without a shell; requires --allow-command; supports env overrides"),
        ToolInfo::new("node_eval", "Run JavaScript with node --input-type=module in cwd; requires --allow-command"),
        ToolInfo::new("python_eval", "Run Python code with python3 in cwd; requires --allow-command"),
        ToolInfo::new("list_package_scripts", "List package.json scripts in cwd"),
        ToolInfo::new("run_package_script", "Run one existing package.json script with npm; requires --allow-command or interactive approval; supports env overrides"),
        ToolInfo::new("git_status", "Read git status --short for cwd"),
        ToolInfo::new("git_diff", "Read git diff for cwd or one path under cwd"),
        ToolInfo::new("git_log", "Read recent git commits for cwd or one path under cwd"),
        ToolInfo::new("git_show", "Read one git object or commit summary; optional path scopes the output"),
        ToolInfo::new("fetch_url", "Fetch one HTTP(S) URL and return text capped at maxBytes with byte count, truncation state, SHA-256, optional timeoutMs, and optional line range"),
        ToolInfo::new("fetch_readable_url", "Fetch one HTTP(S) URL and return simplified readable text capped at maxBytes with byte count, truncation state, SHA-256, optional timeoutMs, and optional line range; supports HTML, JSON, CSV/TSV, RSS/Atom/XML, notebooks, and basic PDF text streams"),
        ToolInfo::new("save_artifact", "Save UTF-8 content into the current session artifacts directory"),
        ToolInfo::new("list_artifacts", "List files in the current session artifact directory"),
        ToolInfo::new("read_artifact", "Read one UTF-8 artifact from the current session artifact directory"),
        ToolInfo::new("ask_user", "Ask the human user a question during an interactive session"),
        ToolInfo::new("todo", "Manage the current session todo list with init, append, start, done, drop, rm, and view operations; supports phased lists"),
        ToolInfo::new("delegate_task", "Run a focused subtask in a fresh Jeden session and return its result"),
        ToolInfo::new("memory", "Remember and recall durable scoped notes across Jeden sessions"),
        ToolInfo::new("mcp_list_tools", "List tools from a configured stdio MCP server"),
        ToolInfo::new("mcp_call_tool", "Call one tool on a configured stdio MCP server"),
        ToolInfo::new("mcp_list_resources", "List resources from a configured stdio MCP server"),
        ToolInfo::new("mcp_read_resource", "Read one resource from a configured stdio MCP server"),
        ToolInfo::new("mcp_list_prompts", "List prompts from a configured stdio MCP server"),
        ToolInfo::new("mcp_get_prompt", "Get one prompt from a configured stdio MCP server"),
    ]
}
