// Generated by scripts/protocol-keys.mjs from
// protocol/schema/v1/envelope.schema.json. Do not edit by hand: change the
// schema and run `npm run generate:protocol`. The drift gate is
// tests/protocol/envelope-keys.mjs.

/** Jeden Session Protocol Envelope v1. */
export const PROTOCOL_TITLE = "Jeden Session Protocol Envelope v1";

/** Every field `request` allows, in schema order. */
export const REQUEST_KEYS = ["type", "id", "method", "params", "meta"] as const;
/** The fields `request` requires. */
export const REQUEST_REQUIRED = ["type", "id", "method", "params", "meta"] as const;

/** Every field `requestMeta` allows, in schema order. */
export const REQUEST_META_KEYS = ["protocolVersion", "idempotencyKey", "deadline", "traceId"] as const;
/** The fields `requestMeta` requires. */
export const REQUEST_META_REQUIRED = ["protocolVersion", "idempotencyKey"] as const;

/** Every field `response` allows, in schema order. */
export const RESPONSE_KEYS = ["type", "id", "result"] as const;
/** The fields `response` requires. */
export const RESPONSE_REQUIRED = ["type", "id", "result"] as const;

/** Every field `event` allows, in schema order. */
export const EVENT_KEYS = ["type", "sessionId", "streamId", "sequence", "cursor", "eventId", "requestId", "kind", "payload"] as const;
/** The fields `event` requires. */
export const EVENT_REQUIRED = ["type", "sessionId", "streamId", "sequence", "cursor", "eventId", "kind", "payload"] as const;

/** Every field `error` allows, in schema order. */
export const ERROR_ENVELOPE_KEYS = ["type", "id", "error"] as const;
/** The fields `error` requires. */
export const ERROR_ENVELOPE_REQUIRED = ["type", "error"] as const;

/** Every field `errorBody` allows, in schema order. */
export const ERROR_BODY_KEYS = ["code", "message", "retryable", "details"] as const;
/** The fields `errorBody` requires. */
export const ERROR_BODY_REQUIRED = ["code", "message", "retryable", "details"] as const;

/** Every field `replayParams` allows, in schema order. */
export const REPLAY_PARAMS_KEYS = ["sessionId", "cursor", "limit"] as const;
/** The fields `replayParams` requires. */
export const REPLAY_PARAMS_REQUIRED = ["sessionId"] as const;
