#!/usr/bin/env python3
"""Build the goal-distillation corpus from local coding-agent session history.

Sources:
  - Omp session files (~/.omp/agent/sessions/**/*.jsonl): first user message
    plus the session title generated by Omp's own title pipeline (or set by
    the user). These are the labeled seed pairs.
  - Transcript Lake normalized exports
    (~/.transcript-lake/exports/oko/runtime=<runtime>/*.jsonl): up to
    MAX_PER_SESSION user messages per session for claude/codex/droid/kimi.
    These arrive unlabeled; the teacher pass (label_corpus.py on the GPU
    host) distills goals for them with the same system prompt Jeden uses in
    production.

Output: JSONL rows {"session_id", "runtime", "message", "goal", "goal_source"}
where goal is null for unlabeled rows. Prints corpus statistics to stderr.

Stdlib only; runs on the operator Mac, never touches the network.
"""

import json
import os
import re
import sys
import hashlib
from pathlib import Path

HOME = Path.home()
OMP_SESSIONS = HOME / ".omp" / "agent" / "sessions"
LAKE_EXPORTS = HOME / ".transcript-lake" / "exports" / "oko"

MAX_PER_SESSION = 3
MAX_MESSAGE_CHARS = 4000
MIN_MESSAGE_CHARS = 3
MASKED_MARKER = "[masked:"
LAKED_RUNTIMES = ("claude", "codex", "droid", "kimi")


def iter_jsonl(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                try:
                    yield json.loads(line)
                except json.JSONDecodeError:
                    continue
    except OSError:
        return


def message_text(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for part in content:
            if isinstance(part, dict) and part.get("type") == "text":
                parts.append(str(part.get("text", "")))
        return "\n".join(parts)
    return ""


def keep_message(text):
    text = text.strip()
    if len(text) < MIN_MESSAGE_CHARS or len(text) > MAX_MESSAGE_CHARS:
        return None
    if text.startswith("/"):
        return None
    if MASKED_MARKER in text:
        return None
    return text


def omp_pairs(stats):
    """First user message + session title from raw Omp session files."""
    for path in sorted(OMP_SESSIONS.rglob("*.jsonl")):
        title = None
        title_source = None
        slot_title = None
        slot_source = None
        first_message = None
        for entry in iter_jsonl(path):
            etype = entry.get("type")
            if etype == "title":
                candidate = entry.get("title")
                if isinstance(candidate, str) and candidate.strip():
                    slot_title = candidate.strip()
                    slot_source = entry.get("source") or "auto"
            elif title is None and etype == "title_change":
                # The chronologically first title_change is the one generated
                # from the first user message; later entries are replan
                # refreshes describing a different stage of the session. The
                # fixed-width title slot holds the LATEST title, so it is only
                # a fallback when no title_change was recorded at all.
                candidate = entry.get("title")
                if isinstance(candidate, str) and candidate.strip():
                    title = candidate.strip()
                    title_source = entry.get("source") or "auto"
            if first_message is None and etype == "message":
                message = entry.get("message") or {}
                if message.get("role") == "user":
                    text = keep_message(message_text(message.get("content")))
                    if text:
                        first_message = text
        if title is None and slot_title is not None:
            title = slot_title
            title_source = slot_source
        if first_message is None:
            stats["omp_no_message"] += 1
            continue
        stats["omp_rows"] += 1
        if title is None:
            stats["omp_untitled"] += 1
        yield {
            "session_id": path.stem,
            "runtime": "omp",
            "message": first_message,
            "goal": title,
            "goal_source": f"omp-title-{title_source}" if title else None,
        }


def lake_corpus(stats):
    """User messages from the lake's normalized exports (unlabeled)."""
    for runtime in LAKED_RUNTIMES:
        runtime_dir = LAKE_EXPORTS / f"runtime={runtime}"
        if not runtime_dir.is_dir():
            continue
        for path in sorted(runtime_dir.glob("*.jsonl")):
            seen_session = None
            taken = 0
            for event in iter_jsonl(path):
                if event.get("event_type") != "user":
                    continue
                session_id = event.get("session_id") or path.stem
                if session_id != seen_session:
                    seen_session = session_id
                    taken = 0
                if taken >= MAX_PER_SESSION:
                    continue
                text = keep_message(str(event.get("text") or ""))
                if not text:
                    continue
                taken += 1
                stats[f"{runtime}_rows"] = stats.get(f"{runtime}_rows", 0) + 1
                yield {
                    "session_id": session_id,
                    "runtime": runtime,
                    "message": text,
                    "goal": None,
                    "goal_source": None,
                }


def main():
    stats = {key: 0 for key in ("omp_rows", "omp_no_message", "omp_untitled")}
    rows = []
    seen = {}
    for row in list(omp_pairs(stats)) + list(lake_corpus(stats)):
        digest = hashlib.sha256(
            re.sub(r"\s+", " ", row["message"].strip().lower()).encode("utf-8")
        ).hexdigest()
        if digest in seen:
            stats["duplicates"] = stats.get("duplicates", 0) + 1
            # A duplicate of a labeled row adds nothing; an unlabeled
            # duplicate never displaces a labeled row.
            if seen[digest].get("goal") or not row.get("goal"):
                continue
            seen[digest] = row
        else:
            seen[digest] = row
        rows.append(row)

    out_path = Path(sys.argv[1] if len(sys.argv) > 1 else "corpus.jsonl")
    with open(out_path, "w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")

    labeled = sum(1 for row in rows if row.get("goal"))
    for key in sorted(stats):
        print(f"{key}: {stats[key]}", file=sys.stderr)
    print(f"total_rows: {len(rows)}", file=sys.stderr)
    print(f"labeled_rows: {labeled}", file=sys.stderr)
    print(f"unlabeled_rows: {len(rows) - labeled}", file=sys.stderr)
    print(f"output: {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
